### ISSUE TITLE
logout is resulting in a route that does not exist

### ISSUE THREAD

**Issue by dctoon** [auth0-extensions/auth0-visualstudio-deploy#11]
When clicking the _logout_ button, the user is redirected to `${window.config.BASE_URL}/logout`, but there is no route defined for `/logout` resulting in the error _Cannot GET /api/run/{xxxx}/{xxxx}/logout_

https://github.com/auth0-extensions/auth0-visualstudio-deploy/blob/d290b9aca5d0559e460bc069817c2e614a1fe073/client/actions/auth.js#L8

**Comment by sgmeyer** [comment]
@dctoon can you confirm if this has been resolved and mark this issue as closed?

**Comment by shawnmclean** [comment]
Marking this issue as closed due to no response.
