### ISSUE TITLE
Extension doesn't seem to be working

### ISSUE THREAD

**Issue by shep1987** [auth0-extensions/auth0-visualstudio-deploy#26]
I have tried to setup this extension this morning but with no luck:

Here is the error I am getting:

`12:09:35 PM:
 New webtask request 1530788975154.474172
12:09:36 PM:
 2018-07-05t11:09:36.122z - info: starting visual studio team services deploy extension - version: 2.2.5
12:09:36 PM:
 Unhandled rejection error: failed request: not found(404) - https://<XXXX>.visualstudio.com/<YYY>/_apis/git
at processresponse (/data/_verquire/vso-node-api/3.1.1/node_modules/vso-node-api/restclient.js:60:18)
at /data/_verquire/vso-node-api/3.1.1/node_modules/vso-node-api/restclient.js:148:13
at callback (/data/_verquire/vso-node-api/3.1.1/node_modules/vso-node-api/httpclient.js:135:17)
at handleresult (/data/_verquire/vso-node-api/3.1.1/node_modules/vso-node-api/httpclient.js:151:17)
at incomingmessage.<anonymous> (/data/_verquire/vso-node-api/3.1.1/node_modules/vso-node-api/httpclient.js:162:17)
at emitnone (events.js:72:20)
at incomingmessage.emit (events.js:166:7)
at endreadablent (_stream_readable.js:923:12)
at nexttickcallbackwith2args (node.js:511:9)
at process._tickdomaincallback (node.js:466:17)
12:10:10 PM:
 Finished webtask request 1530788975154.474172 with http 500 in 35134ms`

**Comment by shawnmclean** [comment]
Hi @shep1987, I'll test this out and let you know. Could you let me know if you're running the latest version?

**Comment by shep1987** [comment]
![image](https://user-images.githubusercontent.com/7226370/42451676-ddf26f64-837f-11e8-9595-276657a5f0c7.png)

I am using "2.2" can't see where to get the patch version but the tenant and extension were only setup/installed last week. If there is any troubleshooting I can do from this end please let me know :)

**Comment by fyockm** [comment]
@shep1987 did you follow the [docs for this extension](https://auth0.com/docs/extensions/visual-studio-team-services-deploy)?
There have been no other reports of VS Deployments not working, so it's most likely a config issue.

**Comment by shep1987** [comment]
Hey, sorry have been really busy so apologies for the late reply; I have followed the docs but still gettign the same error... some differences in the payloads being sent i have spotted:

**under "repository"**
Ours
"remoteUrl": "https://xxx.visualstudio.com/--ProjectName--/_git/--RepoName--"
Yours
"remoteUrl": "https://xxx.visualstudio.com/_git/--ProjectName--"

**under "_links"**
Ours
"repository": {
        "href": "https://xxx.visualstudio.com/--ProjectGuid--/_apis/git/repositories/--RepoGuid--"
},
Yours
"repository": {
        "href": "https://xxx.visualstudio.com/_apis/git/repositories/--RepoGuiD--"
},

pusher and ref follow the same pattern

**Comment by shep1987** [comment]
Just tried removing everything and setting it up again but still having the same issue, happy to provide more diagnostic information if you can point me to the right place

**Comment by jmangelo** [comment]
@shep1987 can you ensure that the value you set for `TFS_COLLECTION` is `DefaultCollection`? Azure DevOps does not have the concept of project collections; you have organizations and projects so one of the valid forms to call the API would be `https://<ORGANIZATION>.visualstudio.com/DefaultCollection/_apis/git`.

**Comment by shep1987** [comment]
That was it... sorry to waste peoples time!
