### ISSUE TITLE
Auth0 VSTS extension 2.3  is not working 

### ISSUE THREAD

**Issue by TuanAnh207** [auth0-extensions/auth0-visualstudio-deploy#34]
Step to reproduce bug
-  Install VSTS extension in Auth0 (the displayed version is 2.3)
-  Access the installed extension page 
For more detail please visit https://community.auth0.com/t/vsts-extension-2-3-is-not-working/18727
Response 
{
  "code": 400,
  "message": "Compilation failed: Cannot find module 'auth0-source-control-extension-tools@3.0.9'",
  "error": "Cannot find module 'auth0-source-control-extension-tools@3.0.9'",
  "stack": "Error: Cannot find module 'auth0-source-control-extension-tools@3.0.9'\n    at Function.Module._resolveFilename (module.js:325:15)\n    at Function.WebtaskModule._resolveFilename (/data/sandbox/lib/module.js:49:27)\n    at WebtaskModule.require (/data/sandbox/lib/module.js:102:39)\n    at require (/data/sandbox/lib/module.js:137:21)\n    at Object.module.exports.e.__esModule.default (/data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:7011)\n    at t (/data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:177)\n    at Object.module.exports.e.__esModule.default (/data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:7216)\n    at t (/data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:177)\n    at Object.module.exports.e.__esModule.default (/data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:50103)\n    at t (/data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:177)\n    at Object.module.exports.e.__esModule.default (/data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:55776)\n    at t (/data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:177)\n    at Object.<anonymous> (/data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:34579)\n    at Object.<anonymous> (/data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:36565)\n    at t (/data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:177)\n    at Object.<anonymous> (/data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:59578)\n    at t (/data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:177)\n    at /data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:560\n    at Object.<anonymous> (/data/io/5d9a5bba-0f9f-4d41-a78f-d66746bbdbc2/webtask.js:1:570)\n    at WebtaskModule.compileWebtask (/data/sandbox/lib/module.js:96:34)\n    at defaultJavascriptCompiler (/data/sandbox/lib/compiler.js:119:30)\n    at defaultCompiler (/data/sandbox/lib/compiler.js:128:16)"
}

**Comment by zxan1285** [comment]
Hi @TuanAnh207 
It seems you're trying to run this extension on node4. Due to deprecation, some of new modules might be missing in node4 containers. Could you please try running the extension on node8?

**Comment by TuanAnh207** [comment]
Hi @zxan1285 , it seem to be the problem. Unfortunately, I have no control over the runtime of the extension because it's hosted by Auth0.

**Comment by zxan1285** [comment]
Here's migration docs: https://auth0.com/docs/migrations/guides/extensibility-node8
I should've provide this link in my first comment, sorry.

**Comment by TuanAnh207** [comment]
@zxan1285  thank you very much, you saved my day 👍 .
